delete from DCAB_SCHEDULE_PRE a where a.SCHEDULE_ID in (select b.id from DCAB_SCHEDULE b where b.group_id='GROUP_DM_RPTC')
/
delete from DCAB_SCHEDULE_NODE_FUNC a where a.schedule_id in (select b.id from DCAB_SCHEDULE b where b.group_id='GROUP_DM_RPTC')
/
delete from DCAB_REPORT_MAPPING a where a.schedule_id in (select b.id from DCAB_SCHEDULE b where b.group_id='GROUP_DM_RPTC')
/
delete from DCAB_REPORT_MAPPING a where a.schedule_id in ('SCHEDULE_RC_RPTC_KMHZB01','SCHEDULE_RC_RPTC_WDYWCLMXB01','SCHEDULE_RC_RPTC_BHCL01')
/
delete from DCAB_SCHEDULE a where a.group_id = 'GROUP_DM_RPTC'
/
delete from DCAB_SCHEDULE_GROUP a where a.ID = 'GROUP_DM_RPTC'
/

--rc阶段分组设置
insert into DCAB_SCHEDULE_GROUP (ID, NAME) values ('GROUP_DM_RPTC', '综合报表')
/

--调度任务

-- 资产负债表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_ZCFZB01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 /1 * * ?','资产负债表','RC',1)
/
--调度任务所依赖的任务
INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_ZCFZB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_ZCFZB01','ZCFZB01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_ZCFZB01_A','NODE_RC_A','SCHEDULE_RC_RPTC_ZCFZB01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=ZCFZB01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_ZCFZB01_C','NODE_RC_C','SCHEDULE_RC_RPTC_ZCFZB01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=ZCFZB01',0)
/

-- 利润表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_LRB01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 /1 * * ?','利润表','RC',1)
/
--调度任务所依赖的任务
INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_LRB01','LRB01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_LRB01_A','NODE_RC_A','SCHEDULE_RC_RPTC_LRB01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=LRB01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_LRB01_C','NODE_RC_C','SCHEDULE_RC_RPTC_LRB01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=LRB01',0)
/

-- 科目汇总表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_KMHZB01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 /1 * * ?','科目汇总表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_KMHZB01','KMHZB01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_KMHZB01_A','NODE_RC_A','SCHEDULE_RC_RPTC_KMHZB01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=KMHZB01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_KMHZB01_C','NODE_RC_C','SCHEDULE_RC_RPTC_KMHZB01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=KMHZB01',0)
/

-- 委贷业务存量明细表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_WDYWCLMXB01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 /1 * * ?','委贷业务存量明细表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_WDYWCLMXB01','WDYWCLMXB01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_WDYWCLMXB01_A','NODE_RC_A','SCHEDULE_RC_RPTC_WDYWCLMXB01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=WDYWCLMXB01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_WDYWCLMXB01_C','NODE_RC_C','SCHEDULE_RC_RPTC_WDYWCLMXB01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=WDYWCLMXB01',0)
/

-- 保函存量表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_BHCL01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 /1 * * ?','保函存量表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_BHCL01','BHCL01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_BHCL01_A','NODE_RC_A','SCHEDULE_RC_RPTC_BHCL01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=BHCL01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_BHCL01_C','NODE_RC_C','SCHEDULE_RC_RPTC_BHCL01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=BHCL01',0)
/


-- 普惠金融工作月报表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_PHJR01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 * ? *','普惠金融工作月报表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_PHJR01','PHJR01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_PHJR01_A','NODE_RC_A','SCHEDULE_RC_RPTC_PHJR01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=PHJR01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_PHJR01_C','NODE_RC_C','SCHEDULE_RC_RPTC_PHJR01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=PHJR01',0)
/

-- 非现场监管关键指标
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_FXCJGZB01','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 1,4,7,10 ? *','非现场监管关键指标','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_FXCJGZB01','FXCJGZB01')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_FXCJGZB01_A','NODE_RC_A','SCHEDULE_RC_RPTC_FXCJGZB01','RMM-Service.DataItemValitExecutor','JAVA','contentCode=FXCJGZB01',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_FXCJGZB01_C','NODE_RC_C','SCHEDULE_RC_RPTC_FXCJGZB01','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=FXCJGZB01',0)
/

-- 市场风险资本要求情况表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_G4C00','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 1,4,7,10 ? *','市场风险资本要求情况表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_G4C00','G4C00')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_G4C00_A','NODE_RC_A','SCHEDULE_RC_RPTC_G4C00','RMM-Service.DataItemValitExecutor','JAVA','contentCode=G4C00',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_G4C00_C','NODE_RC_C','SCHEDULE_RC_RPTC_G4C00','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=G4C00',0)
/

-- 银行账簿利率风险计量报表(标准化计量框架简化版)
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_G3301','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 1,4,7,10 ? *','银行账簿利率风险计量报表(标准化计量框架简化版)','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_G3301','G3301')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_G3301_A','NODE_RC_A','SCHEDULE_RC_RPTC_G3301','RMM-Service.DataItemValitExecutor','JAVA','contentCode=G3301',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_G3301_C','NODE_RC_C','SCHEDULE_RC_RPTC_G3301','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=G3301',0)
/

-- 江西省银行业金融机构与融资担保公司担保贷款明细表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_RZDB1','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 1,7 ? *','江西省银行业金融机构与融资担保公司担保贷款明细表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_RZDB1','RZDB1')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_RZDB1_A','NODE_RC_A','SCHEDULE_RC_RPTC_RZDB1','RMM-Service.DataItemValitExecutor','JAVA','contentCode=RZDB1',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_RZDB1_C','NODE_RC_C','SCHEDULE_RC_RPTC_RZDB1','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=RZDB1',0)
/

-- 江西省银行业金融机构与融资担保公司担保贷款报表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_RZDB2','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 1,7 ? *','江西省银行业金融机构与融资担保公司担保贷款报表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_RZDB2','RZDB2')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_RZDB2_A','NODE_RC_A','SCHEDULE_RC_RPTC_RZDB2','RMM-Service.DataItemValitExecutor','JAVA','contentCode=RZDB2',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_RZDB2_C','NODE_RC_C','SCHEDULE_RC_RPTC_RZDB2','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=RZDB2',0)
/

-- 绿色融资统计表
--调度任务
INSERT INTO DCAB_SCHEDULE(ID,TIMEOUT_ID,GROUP_ID,CRON_EXP,SCHEDULE_NAME,SCHEDULE_PHASE,CURTFLAG)
VALUES('SCHEDULE_RC_RPTC_T115','TIMEOUT_DEFAULT','GROUP_DM_RPTC','0 0 6 1 1,7 ? *','绿色融资统计表','RC',1)
/
--调度任务所依赖的任务
--INSERT INTO DCAB_SCHEDULE_PRE VALUES ('SCHEDULE_RC_RPTC_LRB01', 'SCHEDULE_DW_ACCT_BAL', 'NODE_DW_C')
--/
--调度任务频率、权限配置
INSERT INTO DCAB_REPORT_MAPPING(SCHEDULE_ID,REPORT_NO) VALUES('SCHEDULE_RC_RPTC_T115','T115')
/
--调度任务对应的函数
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_T115_A','NODE_RC_A','SCHEDULE_RC_RPTC_T115','RMM-Service.DataItemValitExecutor','JAVA','contentCode=T115',0)
/
INSERT INTO DCAB_SCHEDULE_NODE_FUNC(ID,NODE_ID,SCHEDULE_ID,NAME,TYPE,PARAMS,IS_CONTINUE)
VALUES('FUNC_RC_RPTC_T115_C','NODE_RC_C','SCHEDULE_RC_RPTC_T115','RMM-Service.DataItemCalcAndFillExecutor','JAVA','contentCode=T115',0)
/

commit
/
